export interface GenerusItem {
  id: string;
  nomorUnik: string;
  nama: string;
  jenisKelamin: string;
  kategoriUsia: string;
  kategori?: string | null;
  namaOrtu?: string | null;
  tempatLahir: string | null;
  tanggalLahir: string | null;
  alamat: string | null;
  noTelp: string | null;
  noTelpOrtu?: string | null;
  pendidikan: string | null;
  pekerjaan: string | null;
  statusNikah: string | null;
  jumlahAnak?: number | null;
  anakKe?: number | null;
  jumlahSaudara?: number | null;
  hobi?: string | null;
  makananMinumanFavorit?: string | null;
  suku?: string | null;
  foto?: string | null;
  desaId?: number | null;
  kelompokId?: number | null;
  mandiriDesaId?: number | null;
  mandiriKelompokId?: number | null;
  desaNama?: string | null;
  kelompokNama?: string | null;
  mandiriDesaNama?: string | null;
  mandiriKelompokNama?: string | null;
  role?: string | null;
  email?: string | null;
  passwordPlain?: string | null;
  generusId?: string | null;
  createdAt?: string | null;
  instagram?: string | null;
  kriteriaPasangan?: string | null;
  nomorUrut?: number | null;
  kota?: string | null;
  mandiriDesaKota?: string | null;
  panitiaStatus?: string | null;
  roomVisitCount?: number | null;
  keterangan?: string | null;
}
